datasets: 'datasets.tsv' #tab-delimited table, see README
read_length: 150 #or 100
taxonomic_level: 'G' #options: D,P,C,O,F,G,S
database: "/labs/asbhatt/data/program_indices/kraken2/kraken_custom_oct2018/genbank_bacteria"
#database alternatives (see README):
# /labs/asbhatt/data/program_indices/kraken2/kraken_custom_oct2018/genbank_bacteria
# /labs/asbhatt/data/program_indices/kraken2/kraken_custom_oct2018/genbank_bacteria_complete/
# /labs/asbhatt/data/program_indices/kraken2/kraken_unmod/standard/
# /labs/asbhatt/data/program_indices/kraken2/kraken_unmod/standard_protein/
# /labs/asbhatt/data/program_indices/kraken2/kraken_unmod/nt
# /labs/asbhatt/data/program_indices/kraken2/kraken_unmod/env_nt